spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: IAM
          uri: ${IAM_URL:http://localhost:8080}
          predicates:
            - Path=/iam/api/**, /iam/swagger-ui/**, /iam/v3/**
          filters:
            - StripPrefix=1
        - id: paymaster
          uri: ${PAYMASTER_URL:http://localhost:8080}
          predicates:
            - Path=/paymaster/api/**
          filters:
            - StripPrefix=1
            - IamAuthenticationFilter
        - id: reminder
          uri: ${REMINDER_URL:http://localhost:8080}
          predicates:
            - Path=/reminder/api/**
          filters:
            - StripPrefix=1
            - IamAuthenticationFilter
        - id: UI
          uri: ${MEMBERSHIP_CONSOLE_URL:http://localhost:80}
          predicates:
            - Path=/**

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
    session:
      cookie:
        same-site: strict
  forward-headers-strategy: framework

project:
  name: api-gateway
  version: 1.0.0-SNAPSHOT
  package: cc.rits.membership.console.api_gateway

logging:
  level:
    root: INFO