spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    web-application-type: reactive

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
    session:
      cookie:
        same-site: strict
  forward-headers-strategy: framework

project:
  name: api-gateway
  version: 1.0.0_SNAPSHOT
  package: cc.rits.membership.console.api_gateway

logging:
  level:
    root: INFO